Fix index.md english and word reuse
PurpleI2P/i2pd_docs_en pull request #28
Opened 2019-01-01 21:13 UTC by hugbubby

Some terminology was wrong.

2019-01-02 18:12 UTC, l-n-s commented
Why do you want to use different words? IMO, it doesn't make the message more clear, prove me wrong.

2019-01-02 18:26 UTC, majestrate commented
On Wed, Jan 02, 2019 at 10:12:35AM -0800, l-n-s wrote:
> Why do you want to use different words? IMO, it doesn't make the message more clear, prove me wrong.
these are the gramatically correct english versions of what was being said.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/PurpleI2P/i2pd_docs_en/pull/28#issuecomment-450938781

2019-01-02 19:16 UTC, l-n-s commented
Sure, there are grammar errors in it, they need to be fixed. But this text is very important, it needs to be as simple and clear as possible. We can't swap words for every PR. :)
See my notes.

2019-01-03 21:36 UTC, hugbubby commented
I don't think you understand - this is just the semantically/gramatically correct version of what's being said, in English. It's not just swapping word choice - full-featured isn't a word in the English language.

2019-01-04 07:34 UTC, l-n-s commented
I understand, you are absolutely right. Let me try to explain what I mean here.

I2P terminology is a mess, "I2P" means a lot of things.
I2P is a protocol, I2P is an actual public network, I2P is a software written in Java, I2P is a community project, which develops the software and maintains the network. We're trying to make it a little better in the i2pd's documentation.

We say here, that i2pd is an I2P client implementation. And later in the text, we explain what I2P client is. If we say it's a protocol implementation, we'll need to rewrite the other part, so it can make sense. I'm not sure it will make the message more clear though.

It is also not obvious to me, why have you changed the word "software" to "application" and the word "using" to "traversing"?

Other than that, the patch looks great, thanks for you contribution! :+1:

2019-01-18 08:13 UTC, l-n-s commented
No reply? OK then, I'm going to commit grammar fixes by myself.

2019-01-23 18:55 UTC, hugbubby commented
In English, software doesn't require the article "a", and the closest change I could think of to make the sentence work was to remove "software" and add "application". Traversing is just a more descriptive word.

We can change the header back and instead write "client for the I2P protocol" or "client for the invisible internet protocol", I just wanted to make it clear that I2P was a protocol and i2pd is software for accessing the i2p network.

2021-10-19 03:21 UTC, xanoni requested changes
Lol maybe we should resolve this after almost 3 years. Tried to incorporate people's feedback.

2021-10-19 03:21 UTC, xanoni commented on docs/index.md
> +i2pd (I2P Daemon) is a fully-featured C++ implementation of the I2P protocol.
What about:

`i2pd (I2P Daemon) is a fully-featured I2P client implementation written in C++.`

2021-10-19 03:21 UTC, xanoni commented on docs/index.md
> +All communications over I2P are anonymous and end-to-end encrypted, and participants
OK sure

2021-10-19 03:21 UTC, xanoni commented on docs/index.md
> +An I2P client is an application for building and traversing anonymous I2P
What about:

```
An I2P client is used to build and access anonymous I2P networks.
Such networks are commonly used for both anonymous peer-to-peer
applications (e.g., filesharing, cryptocurrencies) and anonymous client-
server applications (e.g., websites, instant messengers, chat-servers).
```

2022-06-25 23:12 UTC, closed without merging