added install cmake to ubuntu section
PurpleI2P/i2pd_docs_en pull request #93
Opened 2024-03-23 09:15 UTC by maxfry-v6

2024-03-23 15:36 UTC, r4sas requested changes

2024-03-23 15:36 UTC, r4sas commented on docs/devs/building/unix.md
> +    cd i2pd/tests/
Code lines must prepend with tabulation (Tab)

2024-03-23 21:17 UTC, maxfry-v6 commented on docs/devs/building/unix.md
> +    cd i2pd/tests/
fixed

2024-03-24 07:25 UTC, merged

2024-03-24 07:25 UTC, r4sas commented
Thank you!